keys:
  - &primary age1amdd4hu6k0czf3mtlhd03yj3yzkdaynl7q5fdlqmjzpe9pwgxfjs3j0c85
  - &yggdrasil age1xxv54tzxz6n4cp4undmejl2lyd7k7s3yh9q0z6ed83evfuz6asqsqhaduv
  - &loptland age13xshg5e6ucvnu3vqgn344mxpk5kcqutv2lf4gdffvwadq0ku5ewqy4cck6
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups: 
    - age:
      - *primary

  - path_regex: secrets/secrets-yggdrasil.yaml$
    key_groups: 
    - age:
      - *primary
      - *yggdrasil
      
  - path_regex: secrets/secrets-loptland.yaml$
    key_groups: 
    - age:
      - *primary
      - *loptland
