on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      build_x86_64:
        description: "Build x86_64 outputs"
        type: boolean
        default: true
      build_aarch64:
        description: "Build aarch64 outputs"
        type: boolean
        default: true
jobs:
  build-x86_64:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_x86_64 }}
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - name: Build x86_64 outputs
        run: om ci run .#default.x86_64
  build-aarch64:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.build_aarch64 }}
    runs-on: aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - name: Build aarch64 outputs
        run: om ci run .#default.aarch64
