name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀

on: 
  schedule:
    - cron: 0 3 * * *
  push:
  
jobs:
  test:
    runs-on: native

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update flake
        run: | 
          cd ${{ gitea.workspace }}
          nix flake update
      - name: Commit new Flake.lock
        run: |
          git config --local user.email "christoph.hollizeck@hey.com"
          git config --local user.name "forgjo-actions[bot]"
          git commit -a -m "chore: update flake"
      - name: Push changes
        run: git push