on: [push]
jobs:
  test:
    runs-on: native
    steps:
      - run: nix build nixpkgs#hello

      - uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: result/


